const factoryData = {
  "tianzihun": [
    {
      "name": "卡塞尔机械（浙江）有限公司",
      "area": "天子湖镇",
      "sqm": 1350,
      "floor": "2F-5F",
      "rent": "面议",
      "height": "50*28*5.3",
      "structure": "砖结构",
      "load": "1000KG",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丁类",
      "power": "800KVA",
      "support": "有食堂，无宿舍",
      "contact": "崔经理",
      "phone": "15868269855",
      "note": "其中一幢5F有装修",
      "images": [
        "assets/factory_detail_images/detail_094.jpg",
        "assets/factory_detail_images/detail_095.jpg",
        "assets/factory_detail_images/detail_096.jpg",
        "assets/factory_detail_images/detail_097.jpg",
        "assets/factory_detail_images/detail_098.jpg",
        "assets/factory_detail_images/detail_099.jpg"
      ]
    },
    {
      "name": "泷赢环境科技（安吉）有限公司",
      "area": "天子湖镇",
      "sqm": 38000,
      "floor": "2F-4F",
      "rent": "10元-12元",
      "height": "70*65*4.6",
      "structure": "砖混结构",
      "load": "800KG",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丁类",
      "power": "630KVA",
      "support": "有食堂，无宿舍",
      "contact": "吕美",
      "phone": "18957287029",
      "note": "2楼有12.6*63连廊 化工园区",
      "images": [
        "assets/factory_detail_images/detail_089.jpg",
        "assets/factory_detail_images/detail_090.jpg",
        "assets/factory_detail_images/detail_091.jpg",
        "assets/factory_detail_images/detail_092.jpg",
        "assets/factory_detail_images/detail_093.jpg"
      ]
    },
    {
      "name": "浙江博耳新材料有限公司",
      "area": "天子湖镇",
      "sqm": 3425,
      "floor": "2F-3F",
      "rent": "二楼：10元；三楼：5元",
      "height": "2-3F：101.82*30.48*4.5",
      "structure": "砖混结构",
      "load": "2F:1000KG 3F:500KG",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丁类",
      "power": "250KVA",
      "support": "有食堂，无宿舍",
      "contact": "高清",
      "phone": "13777888934",
      "note": "另有办公楼一栋出租（460平方米）3层，化工园区",
      "images": [
        "assets/factory_detail_images/detail_076.jpg",
        "assets/factory_detail_images/detail_077.jpg",
        "assets/factory_detail_images/detail_078.jpg",
        "assets/factory_detail_images/detail_079.jpg",
        "assets/factory_detail_images/detail_080.jpg",
        "assets/factory_detail_images/detail_081.jpg"
      ]
    },
    {
      "name": "浙江登新科技有限公司",
      "area": "天子湖镇",
      "sqm": 2900,
      "floor": "3F",
      "rent": "面议",
      "height": "100*30*4.8",
      "structure": "砖混结构",
      "load": "500KG",
      "crane": "",
      "elevator": "",
      "decoration": "简修",
      "use": "工业",
      "fire": "丁类",
      "power": "400KVA",
      "support": "有食堂，无宿舍",
      "contact": "胡工",
      "phone": "13697246091",
      "note": "另有办公楼2楼出租，已装修完成",
      "images": [
        "assets/factory_detail_images/detail_082.jpg",
        "assets/factory_detail_images/detail_083.jpg",
        "assets/factory_detail_images/detail_084.jpg",
        "assets/factory_detail_images/detail_085.jpg",
        "assets/factory_detail_images/detail_086.jpg",
        "assets/factory_detail_images/detail_087.jpg",
        "assets/factory_detail_images/detail_088.jpg"
      ]
    },
    {
      "name": "浙江坤金科技有限公司",
      "area": "泗安镇",
      "sqm": 3000,
      "floor": "整体",
      "rent": "一楼16；楼上具体面议",
      "height": "10#厂房:1F120.7*24.24*7；2-5F：120.7*24.24*4.5米；（其中2F已出租一半） 7#厂房：66.48*24.24*10米 1#、4#厂房：66.48*43.08*9米 2#、3#、5#、6#厂房:84.48米*43.08*9米",
      "structure": "7#为钢架，1#2#3#4#5#6#为砖结构，10#为钢混结构",
      "load": "10#厂房承重500KG",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丁类",
      "power": "1000KVA",
      "support": "无",
      "contact": "冯少华",
      "phone": "13867117198",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_026.jpg",
        "assets/factory_detail_images/detail_027.jpg",
        "assets/factory_detail_images/detail_028.jpg",
        "assets/factory_detail_images/detail_029.jpg",
        "assets/factory_detail_images/detail_030.jpg",
        "assets/factory_detail_images/detail_031.jpg",
        "assets/factory_detail_images/detail_032.jpg",
        "assets/factory_detail_images/detail_033.jpg"
      ]
    },
    {
      "name": "浙江安誉升科技有限公司",
      "area": "天子湖镇",
      "sqm": 2300,
      "floor": "3F-4F",
      "rent": "面议",
      "height": "3F：51*45*4.5 4F：51*45*4.5",
      "structure": "砖混结构",
      "load": "800KG",
      "crane": "",
      "elevator": "",
      "decoration": "有",
      "use": "工业",
      "fire": "丁类",
      "power": "500KVA",
      "support": "有食堂，无宿舍",
      "contact": "黄总",
      "phone": "13656727116",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_046.jpg",
        "assets/factory_detail_images/detail_047.jpg"
      ]
    },
    {
      "name": "浙江春之丰家用纺织品有限公司",
      "area": "泗安镇",
      "sqm": 5300,
      "floor": "整体1F-3F，单独门禁",
      "rent": "8-9元，具体面谈",
      "height": "100*50*4.2",
      "structure": "砖结构",
      "load": "300KG",
      "crane": "",
      "elevator": "",
      "decoration": "有",
      "use": "工业",
      "fire": "丙类",
      "power": "250KVA",
      "support": "无",
      "contact": "王乐民",
      "phone": "18057161515",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_009.jpg",
        "assets/factory_detail_images/detail_010.jpg",
        "assets/factory_detail_images/detail_011.jpg",
        "assets/factory_detail_images/detail_012.jpg"
      ]
    },
    {
      "name": "浙江智博科技有限公司",
      "area": "天子湖镇",
      "sqm": 3500,
      "floor": "1-3F",
      "rent": "面谈",
      "height": "1F：56.24*28.24*3.5                              2-3F：56.24*.28.24*3",
      "structure": "砖混结构",
      "load": "/",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丙类",
      "power": "150KVA",
      "support": "有食堂，有宿舍",
      "contact": "高莹",
      "phone": "18757273203",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_048.jpg",
        "assets/factory_detail_images/detail_049.jpg",
        "assets/factory_detail_images/detail_050.jpg",
        "assets/factory_detail_images/detail_051.jpg",
        "assets/factory_detail_images/detail_052.jpg"
      ]
    },
    {
      "name": "浙江沈达特种装备科技有限公司",
      "area": "泗安镇",
      "sqm": 2,
      "floor": "2号、3号厂房整体可租",
      "rent": "面议",
      "height": "2号厂房每层面积一致，68*54*6（含办公室）",
      "structure": "钢混结构",
      "load": "200KG",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丙类",
      "power": "1000KVA",
      "support": "无",
      "contact": "时建平",
      "phone": "13868276811",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_020.jpg",
        "assets/factory_detail_images/detail_021.jpg",
        "assets/factory_detail_images/detail_022.jpg",
        "assets/factory_detail_images/detail_023.jpg",
        "assets/factory_detail_images/detail_024.jpg",
        "assets/factory_detail_images/detail_025.jpg"
      ]
    },
    {
      "name": "安吉中新活性白土有限公司",
      "area": "天子湖镇",
      "sqm": 23704,
      "floor": "2-5层",
      "rent": "面议",
      "height": "56.6*83*25",
      "structure": "钢混结构",
      "load": "2层1000KG、3-5层400KG",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丙类",
      "power": "630KVA",
      "support": "无",
      "contact": "吕政辉",
      "phone": "15157255048",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_074.jpg",
        "assets/factory_detail_images/detail_075.jpg"
      ]
    },
    {
      "name": "安吉德康精密铸件 有限公司",
      "area": "天子湖镇",
      "sqm": 1150,
      "floor": "2F-5F",
      "rent": "7",
      "height": "65*18*4.5",
      "structure": "砖结构",
      "load": "450KG",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丁类",
      "power": "800KVA",
      "support": "无",
      "contact": "张正德",
      "phone": "13567276128",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_072.jpg",
        "assets/factory_detail_images/detail_073.jpg"
      ]
    },
    {
      "name": "浙江华蒙环保新材料有限公司",
      "area": "天子湖镇",
      "sqm": 7000,
      "floor": "2F和4F",
      "rent": "面议",
      "height": "2F：100*70*5.5 4F：100*70*5.3",
      "structure": "砖结构",
      "load": "2F：800KG   4F：300KG",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丙类",
      "power": "2000KVA",
      "support": "有食堂，有宿舍",
      "contact": "严剑波",
      "phone": "13588441340",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_067.jpg",
        "assets/factory_detail_images/detail_068.jpg",
        "assets/factory_detail_images/detail_069.jpg",
        "assets/factory_detail_images/detail_070.jpg",
        "assets/factory_detail_images/detail_071.jpg"
      ]
    },
    {
      "name": "浙江华缔药业集团有限责任公司",
      "area": "天子湖镇",
      "sqm": 8000,
      "floor": "1F-3F",
      "rent": "一楼：15元：2-3楼：9元",
      "height": "1F：150*100*4.8 2-3F：150*100*3.8",
      "structure": "砖结构",
      "load": "300KG",
      "crane": "",
      "elevator": "",
      "decoration": "有",
      "use": "工业",
      "fire": "丙类",
      "power": "",
      "support": "有食堂，有宿舍",
      "contact": "周海松",
      "phone": "13306512758",
      "note": "7号厂房是洁净车间",
      "images": [
        "assets/factory_detail_images/detail_060.jpg",
        "assets/factory_detail_images/detail_061.jpg",
        "assets/factory_detail_images/detail_062.jpg",
        "assets/factory_detail_images/detail_063.jpg",
        "assets/factory_detail_images/detail_064.jpg",
        "assets/factory_detail_images/detail_065.jpg",
        "assets/factory_detail_images/detail_066.jpg"
      ]
    },
    {
      "name": "安吉吉元家具有限公司",
      "area": "天子湖镇",
      "sqm": 3500,
      "floor": "2F-3F",
      "rent": "4",
      "height": "80*40*4.5",
      "structure": "钢混结构",
      "load": "500KG",
      "crane": "",
      "elevator": "",
      "decoration": "有",
      "use": "生产",
      "fire": "丙类",
      "power": "250KVA",
      "support": "无",
      "contact": "李敏弟",
      "phone": "18621861568",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_058.jpg",
        "assets/factory_detail_images/detail_059.jpg"
      ]
    },
    {
      "name": "浙江长兴万华包装有限公司",
      "area": "泗安镇",
      "sqm": 1470,
      "floor": "1F",
      "rent": "16-20元",
      "height": "1#：21*70*9；2#：28.5*70*9",
      "structure": "钢结构",
      "load": "/",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丁类",
      "power": "400KVA",
      "support": "有食堂，有宿舍",
      "contact": "谈莉莉",
      "phone": "15268236602",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_013.jpg",
        "assets/factory_detail_images/detail_014.jpg",
        "assets/factory_detail_images/detail_015.jpg",
        "assets/factory_detail_images/detail_016.jpg",
        "assets/factory_detail_images/detail_017.jpg",
        "assets/factory_detail_images/detail_018.jpg",
        "assets/factory_detail_images/detail_019.jpg"
      ]
    },
    {
      "name": "浙江荣正管业有限公司",
      "area": "天子湖镇",
      "sqm": 10000,
      "floor": "1、2、3",
      "rent": "12-10元/平方",
      "height": "127*26*4.5",
      "structure": "砖结构",
      "load": "350KG",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丙类",
      "power": "450KVA",
      "support": "无",
      "contact": "刘女士",
      "phone": "13175235280",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_055.jpg",
        "assets/factory_detail_images/detail_056.jpg",
        "assets/factory_detail_images/detail_057.jpg"
      ]
    },
    {
      "name": "浙江振兴铸造有限公司",
      "area": "天子湖镇",
      "sqm": 2136,
      "floor": "4幢",
      "rent": "15-20元/平方",
      "height": "120.68*50.68*13",
      "structure": "钢结构",
      "load": "/",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丙类",
      "power": "4000KVA",
      "support": "有食堂有宿舍",
      "contact": "汪智斌       张敏",
      "phone": "18606820672   15305725678",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_041.jpg",
        "assets/factory_detail_images/detail_042.jpg",
        "assets/factory_detail_images/detail_043.jpg",
        "assets/factory_detail_images/detail_044.jpg",
        "assets/factory_detail_images/detail_045.jpg"
      ]
    },
    {
      "name": "安吉绿金金属材料有限公司",
      "area": "天子湖镇",
      "sqm": 4000,
      "floor": "1",
      "rent": "15",
      "height": "85*25*13",
      "structure": "钢混结构",
      "load": "5吨/平方米",
      "crane": "",
      "elevator": "",
      "decoration": "简装",
      "use": "工业",
      "fire": "丁类",
      "power": "1800KVA",
      "support": "有食堂，有宿舍",
      "contact": "矫坤远",
      "phone": "15857265711",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_034.jpg",
        "assets/factory_detail_images/detail_035.jpg",
        "assets/factory_detail_images/detail_036.jpg",
        "assets/factory_detail_images/detail_037.jpg",
        "assets/factory_detail_images/detail_038.jpg",
        "assets/factory_detail_images/detail_039.jpg",
        "assets/factory_detail_images/detail_040.jpg"
      ]
    },
    {
      "name": "浙江奥蓝光源科技有限公司",
      "area": "泗安镇",
      "sqm": 1,
      "floor": "1幢1-4楼东、2幢1-4楼、3幢1、3、4楼",
      "rent": "面议",
      "height": "1幢、2幢：1F：84.6*48.27*8.5；2F-4F：84.6*48.27*5 3幢1F：45*43*8.5 2F-4F：45*43*5",
      "structure": "钢结构+钢混结构",
      "load": "500KG",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丁类",
      "power": "315KVA",
      "support": "有食堂，有宿舍",
      "contact": "夏冬仙",
      "phone": "13606810908",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_004.jpg",
        "assets/factory_detail_images/detail_005.jpg",
        "assets/factory_detail_images/detail_006.jpg",
        "assets/factory_detail_images/detail_007.jpg",
        "assets/factory_detail_images/detail_008.jpg"
      ]
    },
    {
      "name": "浙江天璇智控科技有限公司",
      "area": "天子湖镇",
      "sqm": 1,
      "floor": "三楼、四楼",
      "rent": "5-8元；具体面议",
      "height": "3-4F：97.88*36*4.2",
      "structure": "砼框架结构",
      "load": "1F：2000KG；   2F：700KG；    3-4F：350KG",
      "crane": "",
      "elevator": "",
      "decoration": "无装修",
      "use": "工业",
      "fire": "丁类",
      "power": "800KVA",
      "support": "有食堂及宿舍",
      "contact": "华美娇",
      "phone": "18257540842",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_001.jpg",
        "assets/factory_detail_images/detail_002.jpg",
        "assets/factory_detail_images/detail_003.jpg"
      ]
    },
    {
      "name": "浙江弗耐特环保机械制造有限公司",
      "area": "天子湖镇",
      "sqm": 35000,
      "floor": "一楼面积4200平方米，层高10米、二楼、三楼、四楼层高4米6，二楼、三楼、四楼面积各7000平方米",
      "rent": "一楼：15-18元；二-四楼：6-9元；具体面议",
      "height": "长119.2米*宽58.24米，一楼10米，2-4楼4.6米",
      "structure": "框架结构",
      "load": "600kg/平方米",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丙类",
      "power": "400KVA",
      "support": "无",
      "contact": "冯国建",
      "phone": "13685758188",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_053.png",
        "assets/factory_detail_images/detail_054.png"
      ]
    },
    {
      "name": "浙江蔓蒂科技有限公司",
      "area": "天子湖镇",
      "sqm": 5000,
      "floor": "3楼",
      "rent": "5元",
      "height": "114.8*42（净高3.2米）",
      "structure": "砖结构",
      "load": "450KG",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丙类",
      "power": "630KVA",
      "support": "食堂",
      "contact": "顾翔",
      "phone": "13587913646",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_100.png",
        "assets/factory_detail_images/detail_101.png",
        "assets/factory_detail_images/detail_102.png",
        "assets/factory_detail_images/detail_103.png"
      ]
    },
    {
      "name": "浙江以勒机械科技有限公司",
      "area": "天子湖镇",
      "sqm": 10560,
      "floor": "2",
      "rent": "一楼：18-20元；二楼：16元；总租16元",
      "height": "一楼面积87*62 高7.5米 二楼面积87*70  高5.5米",
      "structure": "框架结构",
      "load": "2000KG",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丁类",
      "power": "2400KVA",
      "support": "宿舍",
      "contact": "方国庆",
      "phone": "15857252791",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_104.jpg",
        "assets/factory_detail_images/detail_105.jpg",
        "assets/factory_detail_images/detail_106.jpg"
      ]
    },
    {
      "name": "浙江美能电气有限公司",
      "area": "天子湖镇",
      "sqm": 25346,
      "floor": "一号车间",
      "rent": "面谈",
      "height": "138*30*6",
      "structure": "/",
      "load": "/",
      "crane": "",
      "elevator": "",
      "decoration": "简装",
      "use": "工业",
      "fire": "丙类",
      "power": "6000KVA",
      "support": "食堂、宿舍",
      "contact": "任宝荣",
      "phone": "13735125028",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_138.jpg",
        "assets/factory_detail_images/detail_139.jpg",
        "assets/factory_detail_images/detail_140.jpg",
        "assets/factory_detail_images/detail_141.jpg"
      ]
    },
    {
      "name": "浙江鸿云翔橡塑机械有限公司",
      "area": "泗安镇",
      "sqm": 2000,
      "floor": "一层",
      "rent": "面议",
      "height": "98*22*13",
      "structure": "钢结构",
      "load": "/",
      "crane": "",
      "elevator": "",
      "decoration": "有",
      "use": "工业",
      "fire": "丙类",
      "power": "",
      "support": "食堂宿舍均由、水电气全通",
      "contact": "霍明霞",
      "phone": "15268272986",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_132.jpg",
        "assets/factory_detail_images/detail_133.jpg",
        "assets/factory_detail_images/detail_134.jpg"
      ]
    },
    {
      "name": "安吉吉满盛地板有限公司",
      "area": "天子湖镇",
      "sqm": 4558,
      "floor": "2",
      "rent": "一楼单价10元；二楼单价5元",
      "height": "90*25*4",
      "structure": "砖结构",
      "load": "800",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丙类",
      "power": "1250KVA",
      "support": "无",
      "contact": "方亮香",
      "phone": "13587917112",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_110.jpg",
        "assets/factory_detail_images/detail_111.jpg",
        "assets/factory_detail_images/detail_112.jpg",
        "assets/factory_detail_images/detail_113.jpg"
      ]
    },
    {
      "name": "浙江优凯信科技有限公司",
      "area": "天子湖镇",
      "sqm": 20080,
      "floor": "4",
      "rent": "16",
      "height": "76*66*5",
      "structure": "砖混结构",
      "load": "350",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丙类",
      "power": "500KVA",
      "support": "无",
      "contact": "泮燕",
      "phone": "13567291163",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_107.jpg",
        "assets/factory_detail_images/detail_108.jpg",
        "assets/factory_detail_images/detail_109.jpg"
      ]
    },
    {
      "name": "浙江朗闰汽配有限公司",
      "area": "天子湖镇",
      "sqm": 9216,
      "floor": "2、3",
      "rent": "5",
      "height": "128*36*4.8",
      "structure": "框架结构",
      "load": "500",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丙类",
      "power": "100KVA",
      "support": "无",
      "contact": "杨引航",
      "phone": "13252039969",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_114.jpg",
        "assets/factory_detail_images/detail_115.jpg",
        "assets/factory_detail_images/detail_116.jpg",
        "assets/factory_detail_images/detail_117.jpg"
      ]
    },
    {
      "name": "湖州安迪信精密科技有限公司",
      "area": "天子湖镇",
      "sqm": 28115,
      "floor": "1层和2层",
      "rent": "一层25,2层12",
      "height": "一层：110*41*9 二层：110*41*4.5",
      "structure": "混凝土",
      "load": "1000",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丙类",
      "power": "600KV",
      "support": "有",
      "contact": "张心杰",
      "phone": "18358186170",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_118.jpg",
        "assets/factory_detail_images/detail_119.jpg",
        "assets/factory_detail_images/detail_120.jpg"
      ]
    },
    {
      "name": "浙江润格木业科技有限公司",
      "area": "泗安镇",
      "sqm": 6680,
      "floor": "1",
      "rent": "16",
      "height": "1#厂房二楼长81.98米宽18.24米高4.8米 4#厂房二楼长61.04米宽21.24米高4.8米 5#厂房二楼长61.04米宽21.24米高4.8米 6#厂房二楼长61.04米宽21.24米高4.8米 7#厂房二楼长61.04米宽21.24米高4.8米",
      "structure": "钢混结构",
      "load": "500",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丙类",
      "power": "1000KVA",
      "support": "有",
      "contact": "陈伟达",
      "phone": "18867536753",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_135.jpg",
        "assets/factory_detail_images/detail_136.jpg",
        "assets/factory_detail_images/detail_137.jpg"
      ]
    },
    {
      "name": "浙江科扬幕墙有限公司",
      "area": "天子湖镇",
      "sqm": 4000,
      "floor": "1",
      "rent": "16",
      "height": "120*80*12.5米",
      "structure": "钢结构",
      "load": "/",
      "crane": "",
      "elevator": "",
      "decoration": "简装",
      "use": "工业",
      "fire": "丁类",
      "power": "250KVA",
      "support": "无",
      "contact": "潘志刚",
      "phone": "13605809397",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_123.jpg",
        "assets/factory_detail_images/detail_124.jpg",
        "assets/factory_detail_images/detail_125.jpg"
      ]
    },
    {
      "name": "浙江吉木数码印刷板材有限公司",
      "area": "天子湖镇",
      "sqm": 13800,
      "floor": "1",
      "rent": "16-20，具体根据租的面积和年限再谈。",
      "height": "L型，一边120mx41m高10米，一边128mX41m高、10米。二楼92mX41m高5.5米。共约13800m2出租。",
      "structure": "砖结构",
      "load": "/",
      "crane": "",
      "elevator": "",
      "decoration": "简装",
      "use": "工业",
      "fire": "丁类",
      "power": "3150KVA",
      "support": "食堂寝室配套",
      "contact": "王欣",
      "phone": "13906816233",
      "note": "可分租",
      "images": [
        "assets/factory_detail_images/detail_126.jpg",
        "assets/factory_detail_images/detail_127.jpg",
        "assets/factory_detail_images/detail_128.jpg",
        "assets/factory_detail_images/detail_129.jpg",
        "assets/factory_detail_images/detail_130.jpg",
        "assets/factory_detail_images/detail_131.jpg"
      ]
    },
    {
      "name": "安吉金麟机械有限公司",
      "area": "天子湖镇",
      "sqm": 7000,
      "floor": "整体",
      "rent": "面谈",
      "height": "1幢长65米宽15米高4.2米，2幢55米*30米",
      "structure": "钢结构，砖混结构",
      "load": "/",
      "crane": "",
      "elevator": "",
      "decoration": "简装",
      "use": "工业",
      "fire": "丁类",
      "power": "1000KVA",
      "support": "无",
      "contact": "桂在平",
      "phone": "13868280897",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_121.jpg",
        "assets/factory_detail_images/detail_122.jpg"
      ]
    },
    {
      "name": "浙江中茂耐火材料有限公司",
      "area": "泗安镇",
      "sqm": 1266,
      "floor": "1",
      "rent": "面谈",
      "height": "52米*24米*8米",
      "structure": "砖混结构",
      "load": "/",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丙",
      "power": "200KVA",
      "support": "无",
      "contact": "徐伟义",
      "phone": "13957259948",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_142.jpg",
        "assets/factory_detail_images/detail_143.jpg",
        "assets/factory_detail_images/detail_144.jpg"
      ]
    },
    {
      "name": "浙江荣欣钢构有限公司",
      "area": "泗安镇",
      "sqm": 8000,
      "floor": "1",
      "rent": "面谈",
      "height": "二连跨：180*24*11；120*24*11",
      "structure": "钢结构",
      "load": "/",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丁类",
      "power": "800KVA",
      "support": "有食堂及宿舍",
      "contact": "朱军",
      "phone": "13968009818",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_145.jpg",
        "assets/factory_detail_images/detail_146.jpg",
        "assets/factory_detail_images/detail_147.jpg",
        "assets/factory_detail_images/detail_148.jpg"
      ]
    },
    {
      "name": "浙江宇阳电力设备有限公司",
      "area": "天子湖镇",
      "sqm": 3716,
      "floor": "1",
      "rent": "12-13，具体面谈",
      "height": "76.55*48.55*11",
      "structure": "钢结构",
      "load": "500",
      "crane": "",
      "elevator": "",
      "decoration": "简装",
      "use": "工业",
      "fire": "丁戊类",
      "power": "250KVA",
      "support": "无",
      "contact": "张天锋",
      "phone": "13967278632",
      "note": "部分有夹层，夹层2000方为无证建筑，可分租",
      "images": [
        "assets/factory_detail_images/detail_149.jpg",
        "assets/factory_detail_images/detail_150.jpg",
        "assets/factory_detail_images/detail_151.jpg"
      ]
    },
    {
      "name": "浙江裕达鞋业有限公司",
      "area": "泗安镇",
      "sqm": 15855,
      "floor": "整体",
      "rent": "租10-12元/每平方米/月",
      "height": "86.56长*48.24宽；层高：3.8米（面积：12526.96） 宿舍楼食堂：四层 2438.32平方米",
      "structure": "砖混结构",
      "load": "500公斤/每平方米",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丁类",
      "power": "400KVA",
      "support": "食堂、寝室配套",
      "contact": "李芹萍",
      "phone": "13506720930",
      "note": "总面积15855.29平方米含食堂、宿舍、仓库",
      "images": []
    },
    {
      "name": "天衡实业投资有限公司",
      "area": "天子湖镇",
      "sqm": 22600,
      "floor": "1幢4层、2幢3层4层、3幢3层4层、4幢3层4层",
      "rent": "8至12",
      "height": "1幢（一层：长96米*宽45米*高7.9米，二层三层四层长96米*宽45米*高4.8米）、2幢（一层：长84米*宽45米*高7.9米，二层三层四层长84米*宽45米*高4.8米）、3幢（一层：长72米*宽45米*高7.9米，二层三层四层长72米*宽45米*高4.8米）、4幢（一层：长71.74米*宽50米*高7.9米，二层三层四层长71.74米*宽50米*高4.8米）",
      "structure": "钢筋混凝土",
      "load": "一层1000、二层800、三层四层500",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "生产制造、仓储",
      "fire": "丙类",
      "power": "4400kv",
      "support": "无宿舍，可同时容纳200人就餐，另有单独包厢",
      "contact": "王道州",
      "phone": "17857600723",
      "note": "/",
      "images": []
    },
    {
      "name": "西湖科创园",
      "area": "泗安镇",
      "sqm": 4500,
      "floor": "二期1号楼东1-2-3层",
      "rent": "13.5",
      "height": "一层高8.5二层高6.5三层高6.5",
      "structure": "砖混",
      "load": "1000",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "装配",
      "fire": "丙",
      "power": "3150kwh",
      "support": "食堂、宿舍",
      "contact": "余明祥",
      "phone": "13905824482",
      "note": "/",
      "images": []
    },
    {
      "name": "创新综合体",
      "area": "天子湖镇",
      "sqm": 60000,
      "floor": "1号楼",
      "rent": "15",
      "height": "一层高8二层高5.5三层高5.5四层高5.5",
      "structure": "砖混",
      "load": "1000",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丙",
      "power": "10000kwh",
      "support": "无",
      "contact": "余明祥",
      "phone": "13905824482",
      "note": "/",
      "images": []
    },
    {
      "name": "蒲公英厂区",
      "area": "泗安镇",
      "sqm": 5000,
      "floor": "1层",
      "rent": "12",
      "height": "一层高10",
      "structure": "钢结构",
      "load": "/",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丙",
      "power": "3500kwh",
      "support": "食堂、宿舍",
      "contact": "余明祥",
      "phone": "13905824482",
      "note": "/",
      "images": []
    },
    {
      "name": "共创小微园",
      "area": "天子湖镇",
      "sqm": 1,
      "floor": "1",
      "rent": "面谈",
      "height": "1楼层高6米；81.3*48.3",
      "structure": "砖结构",
      "load": "1吨/平方米",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丙类",
      "power": "6号楼250KVA；7-10号楼2000KVA；1-3-4号楼650KVA",
      "support": "有食堂无宿舍",
      "contact": "叶长春",
      "phone": "13587911256",
      "note": "/",
      "images": []
    },
    {
      "name": "浙江安吉华翰实业有限公司",
      "area": "天子湖镇",
      "sqm": 7000,
      "floor": "5",
      "rent": "面谈",
      "height": "1楼6米左右；2-5层5米",
      "structure": "砖结构",
      "load": "1楼1000kg/平方米；2-5楼800kg/平方米",
      "crane": "",
      "elevator": "",
      "decoration": "简装",
      "use": "工业",
      "fire": "丁类",
      "power": "650kv",
      "support": "有食堂无宿舍",
      "contact": "董小顺",
      "phone": "13505823159",
      "note": "",
      "images": []
    },
    {
      "name": "长兴富长实业有限公司 （原正轩厂房）",
      "area": "泗安镇",
      "sqm": 6660,
      "floor": "3号厂房",
      "rent": "自起租日12元/月2年后重新商议",
      "height": "108*53.56*12.15",
      "structure": "钢结构",
      "load": "地面1500kg/㎡",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丁",
      "power": "无单独配电房",
      "support": "有食堂无宿舍",
      "contact": "曾鹏（物业）",
      "phone": "18367299191",
      "note": "",
      "images": []
    },
    {
      "name": "浙江鸿御新材料科技有限公司",
      "area": "天子湖镇",
      "sqm": 8888,
      "floor": "2-4层",
      "rent": "8",
      "height": "70*60*4.8",
      "structure": "钢结构",
      "load": "350",
      "crane": "",
      "elevator": "",
      "decoration": "无",
      "use": "工业",
      "fire": "丁",
      "power": "2000",
      "support": "",
      "contact": "舒毅",
      "phone": "18329190693",
      "note": "",
      "images": [
        "assets/factory_detail_images/detail_152.jpg",
        "assets/factory_detail_images/detail_153.jpg",
        "assets/factory_detail_images/detail_154.jpg"
      ]
    },
  ],
  "sian": []
};